import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import "../../globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const garamond = Cormorant_Garamond({
  weight: '400', // Only 400 is available for Reggae One
  subsets: ['latin'],
  variable: "--font-cormorant-garamond"
});

export const metadata: Metadata = {
  title: "SwitchFi",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/Exchange.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
        className={`${geistSans.variable} ${geistMono.variable} ${garamond.className} antialiased grid grid-rows-12 h-dvh`}
      >
        <Header />
        {children}
      </main>
  );
}
