import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import Navigation from "@/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SwitchFi",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/Exchange.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-12 h-screen`}
      >
        <Header />
        {children}
        <Navigation />
      </main>
  );
}
